### ISSUE TITLE
How to load images in an async manner ?

### ISSUE THREAD

**Issue by MaG21** [ahmetkgunay/CollageView#1]
This library needs images from the very beginning to work properly, which make the task of retrieving data from the outside without blocking the user interface somewhat difficult.

I'm sure because of [THIS LINE](https://github.com/ahmetkgunay/CollageView/blob/master/Source/CollageView.swift#L83)

```swift
assert(rowOrColoumnCount != 0, "Row or Coloumn Count must be more than 0")
assert(itemCount >= rowOrColoumnCount, "Image count can not be more than row Count")
```

am I wrong? if so, how can I load the collage asynchronously?

**Comment by ahmetkgunay** [comment]
you can fetch async images and set them in:

But firstly you should know just the count of total images.

func collageView(_ collageView: CollageView, configure itemView: CollageItemView, at index: Int)

should look like:

    func collageView(_ collageView: CollageView, configure itemView: CollageItemView, at index: Int) {
        
        //
        // MAGIC is in this code block
        // You can prepare your item here also,
        // You can fetch Images from Remote here!,
        // Customize UI for item, and etc..
        
        imageFromServerURL(urlString: "imageUrlString") { (image, error) in
            
            itemView.image = image
        }
        
        itemView.layer.borderWidth = 3
        
        if index == shownImagesCount - 1 {
            
            addBlackViewAndLabel(to: itemView)
        }
    }

**Comment by ahmetkgunay** [comment]
You can use Kingfisher library to fetch async images.

https://github.com/onevcat/Kingfisher

**Comment by MaG21** [comment]
> you can fetch async images and set them in:
> 
> But firstly you should know just the count of total images.

That's escentially the problem.

I don't know how many images I will be loading until the request is done. However, I think it wouldn't be wise to stop the execution of the application waiting the server's response to know the image count.

**Comment by ahmetkgunay** [comment]
OK, I fixed this issue and pushed to master thanks for your feedback!! Appreciate it

**Comment by MaG21** [comment]
Many thanks. I'd be testing the new changes tonight.

**Comment by ahmetkgunay** [comment]
Please Check the new release at https://github.com/ahmetkgunay/CollageView/releases/tag/1.0.4

And also I updated the Cocoapods as the new version is 1.04
